name: kmis
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - pytorch-lightning
  - ray-tune
  - pyg
  - scikit-learn
  - numpy
  - pandas
  - fire
  - matplotlib
  - seaborn
  - networkx
  - tqdm
  - h5py
  - pip
  - pip:
    - git+https://github.com/pyg-team/pytorch_geometric.git