name: kmis
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - pytorch=1.8.1
  - torchvision=0.9.1
  - torchaudio=0.8.1
  - pytorch-lightning=1.4
  - ray-tune
  - pyg
  - scikit-learn
  - setuptools=59.5.0
  - numpy
  - pandas
