name: kmis
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.8
  - cpuonly
  - pytorch=1.8.1
  - torchvision=0.9.1
  - torchaudio=0.8.1
  - pytorch-lightning=1.4
  - setuptools=59.5.0
  - ray-tune
  - pyg
  - scikit-learn
  - numpy
  - pandas
  - fire
  - matplotlib
  - seaborn
  - networkx
  - tqdm
  - h5py