name: kmis
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - scikit-learn
  - pytorch-lightning=1.4
  - setuptools=59.5.0
  - ray-tune
  - numpy
  - pandas
  - fire
  - matplotlib
  - seaborn
  - networkx
  - tqdm
  - h5py
  - pip
  - pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - -f https://data.pyg.org/whl/torch-1.7.1+cu101.html
    - torch==1.7.1+cu101
    - torchvision==0.8.2+cu101
    - torchaudio==0.7.2
    - torch-sparse
    - torch-scatter
    - torch-cluster
    - torch-geometric
